// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import OnePagerThemeController from "./one_pager_theme_controller"
application.register("one-pager-theme", OnePagerThemeController)

import SortableLinksController from "./sortable_links_controller"
application.register("sortable-links", SortableLinksController)

import UrlController from "./url_controller"
application.register("url", UrlController)
